name: 'Bug report'
title: '[BUG]: [COMPONENT]: YOUR_ISSUE_TITLE_HERE_REPLACE_ME'
description: Tell us about a bug you may have identified in EDS
labels: [bug, earth, 'status: waiting for maintainer']
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting an issue :pray:.

        This issue tracker is for reporting reproducible bugs found in [Earth Design System](https://earth.anywhere.co/)
        If you have a question about how to achieve something and are struggling, please post a question with clear description 
        of what help is required in either of the way
          - Reach out to one of the core team members
            @mateusz-kopec-anywhere @TajmulAnsary @thanix-k @nandhiniG
          - Common Collab(Eds Query Hub) 


        Before submitting a new bug/issue, please check the links below to see if there is a solution or question posted there already:
         - EDS's [Issue's tab](https://github.com/Adaptavant/awds/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen+label%3Aearth)
         - EDS's [closed issues tab](https://github.com/Adaptavant/awds/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aopen+label%3Aearth)


        The more information you fill in, the better the team can help you.

        **Please select the package and specify the version:**

  - type: dropdown
    id: package
    attributes:
      label: EDS Package
      description: Select the EDS package you are using.
      options:
        - 'core' # This will be the default selected option
        - 'brands'
        - 'translations'
        - 'fonts'
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: EDS Version
      description: |
        - Please let us know the exact version of the EDS package that you were using when the issue occurred. If you are using an older version, check to see if your bug has already been solved in the latest version. 
        - Please don't just put in "latest", as this is subject to change.
      placeholder: ex. 1.3.0
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Describe the Bug
      description:
        Provide a clear and concise description of the challenge you are running
        into.
    validations:
      required: true
  - type: input
    id: app_name
    attributes:
      label: Application or Brand Name
      description: Please provide the microfrontend app name or the product name
      placeholder: ex. Notifications || Reviews
    validations:
      required: true
  - type: dropdown
    id: env_type
    attributes:
      label: Environment
      description: Select the environment where the issue was observed.
      options:
        - 'Prod'
        - 'Staging'
        - 'Dev'
    validations:
      required: true
  - type: input
    id: link
    attributes:
      label: Your App Url
      description:
        Provide the deployed version of the application to verify the bug. In
        case of dev env , share the playroom snippet Issue will be closed if
        playroom snippet attached for envs other than dev.
      placeholder: |
        ex. https://thinkmill.staging.setmore.com/beta
    validations:
      required: true
  - type: markdown
    id: prototype-app-link
    attributes:
      label: Prototype
      description: If Your App Url, or playroom snippet is not possible to add, we encourage you to use "Prototype" app inside "awds" repo
      placeholder: |
        Add your code to the `apps/prototypes/src/pages/index.tsx` which is the Next Js starter kit and share us the branch, tag or commit id.
        You can run prototype locally by `pnpm dev:prototypes` command. This will help us to get the environment and steps that lead to the bug.
      validations:
        required: false
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce the Bug or Issue
      description: Describe the steps we have to take to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: Provide a clear and concise description of what you expected to happen.       
      placeholder: |
        As a user, I expected ___ behavior but i am seeing ___
    validations:
      required: true
  - type: textarea
    id: screenshots_or_videos
    attributes:
      label: Screenshots or Videos
      description: |
        If applicable, add screenshots or a video to help explain your problem.
        For more information on the supported file image/file types and the file size limits, please refer
        to the following link: https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/attaching-files
      placeholder: |
        You can drag your video or image files inside of this editor ↓
  - type: input
    id: os
    attributes:
      label: Operating System Version
      description: What operating system are you using?
      placeholder: |
        - OS: [ex. macOS, Windows, Linux]
    validations:
      required: true
  - type: dropdown
    id: browser_type
    attributes:
      label: Browser
      description: Select the browsers where the issue can be reproduced (that you know of).        
      options:
        - 'Chrome'
        - 'Firefox'
        - 'Safari'
        - 'Edge'
        - 'Opera'
        - 'Other (add additonal context)'
    validations:
      required: true
  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: Please let us know how critical this bug is to you. Your feedback helps us prioritize effectively.
      options:
          - 'Critical - Severely impacts all users'
          - 'Highest - Blocks key functionality or major feature releases'
          - 'High - Affects features; temporary workarounds is sufficient'
          - 'Medium - Minor inconvenience or cosmetic issue'
          - 'Low - Non-essential, but would be nice to fix'
    validations:
        required: true
  - type: checkboxes
    id: agrees-to-terms
    attributes:
      label: Terms
      description:
        By submitting this issue, you agree to verify that you have followed the
        requirements outlined above to the best of your ability.
      options:
        - label:
            I understand that if my bug cannot be reliable reproduced in a
            debuggable environment, it will probably not be fixed and this issue
            may even be closed.
          required: true
