name: 'Bug report'
title: "[BUG] - YOUR_ISSUE_TITLE_HERE_REPLACE_ME"
description: Tell us about a bug you may have identified in EDS
labels: [bug,earth]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for reporting an issue :pray:.

        This issue tracker is for reporting reproducible bugs found in [Earth Design System](https://earth.anywhere.co/)
        If you have a question about how to achieve something and are struggling, please post a question
        either of the [Anywhereworks channel](https://hub.anywhereworks.com/connect)
          - Reach out to one of the team members
          - Common Collab(Eds Query Hub)


        Before submitting a new bug/issue, please check the links below to see if there is a solution or question posted there already:
         - EDS's [Issue's tab](https://github.com/nandhiniG/storybook-demo/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc)
         - EDS's [closed issues tab](https://github.com/nandhiniG/storybook-demo/issues?q=is%3Aissue+sort%3Aupdated-desc+is%3Aclosed)


        The more information you fill in, the better the team can help you.
  - type: input
    id: version
    attributes:
      label: EDS Version
      description: |
        - Please let us know the exact version of the EDS package that you were using when the issue occurred. If you are using an older version, check to see if your bug has already been solved in the latest version. 
        - Please don't just put in "latest", as this is subject to change.
      placeholder: ex. 1.3.0
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: Provide a clear and concise description of the challenge you are running into.
    validations:
      required: true
  - type: input
    id: app_name
    attributes:
      label: Application or Brand Name
      description: |
        Please provide the microfrontend app name or the product name
      placeholder: ex. Notifications || Reviews
    validations:
      required: true 
  - type: dropdown
    id: env_type
    attributes:
      label: Environment
      description: Select the environment where the issue was observed.
      options:
        - "Prod"
        - "Staging"
        - "Dev"
    validations:
      required: true       
  - type: input
    id: link
    attributes:
      label: Your App Url
      description: Provide the deployed version of the application to verify the bug 
      placeholder: |
        e.g. https://thinkmill.staging.setmore.com/beta
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce the Bug or Issue
      description: Describe the steps we have to take to reproduce the behavior.
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: Provide a clear and concise description of what you expected to happen.
      placeholder: |
        As a user, I expected ___ behavior but i am seeing ___
    validations:
      required: true
  - type: textarea
    id: screenshots_or_videos
    attributes:
      label: Screenshots or Videos
      description: |
        If applicable, add screenshots or a video to help explain your problem.
        For more information on the supported file image/file types and the file size limits, please refer
        to the following link: https://docs.github.com/en/github/writing-on-github/working-with-advanced-formatting/attaching-files
      placeholder: |
        You can drag your video or image files inside of this editor ↓
  - type: input
    id: os
    attributes:
      label: Operating System Version
      description: What operating system are you using?
      placeholder: |
        - OS: [e.g. macOS, Windows, Linux]
    validations:
      required: true
  - type: dropdown
    id: browser_type
    attributes:
      label: Browser
      description: Select the browsers where the issue can be reproduced (that you know of).
      options:
        - "Chrome"
        - "Firefox"
        - "Safari"
        - "Edge"
        - "Opera"
        - "Other (add additonal context)"
    validations:
      required: true