name: Feature request
title: '[Feature]: YOUR_FEATURE_TITLE_HERE_REPLACE_ME'
description: Suggest a new idea or component for Earth Design System
labels: ['earth, feature request, status: waiting for maintainer']
body:
  - type: markdown
    attributes:
      value: |
        Thanks for contributing by creating an issue! ❤️ Please provide a searchable summary of the issue in the title above ⬆️.
        This issue form is for requesting features only! For example, requesting a new component, behavior, etc.
        If you want to report a bug, please use the [bug report form](https://github.com/Adaptavant/awds/issues/new?assignees=&labels=bug%2Cearth%2Cstatus%3A+waiting+for+maintainer&projects=&template=bug_report.yml&title=%5BBUG%5D%3A+%5BCOMPONENT%5D%3A+YOUR_ISSUE_TITLE_HERE_REPLACE_ME).
        If you want to share feedback about the documentation, please use the [doc feedback form](https://github.com/Adaptavant/awds/issues/new?assignees=&labels=earth%2Cstatus%3A+waiting+for+maintainer%2Csupport%3A+docs-feedback&projects=&template=docs_feedback.yml&title=%5BDOCS%5D%3A+%5BPAGE%5D%3A+YOUR_ISSUE_TITLE_HERE_REPLACE_ME).
  - type: checkboxes
    id: duplicate-issue
    attributes:
      label: Not Duplicate Request
      description: |
        Your issue may have already been reported! First search for duplicates among the [existing issues](https://github.com/Adaptavant/awds/issues).
        We roll bug fixes, performance enhancements, and other improvements into new releases. Please test your expected behavior in the latest version.
      options:
        - label:
            I've searched for existing issues and tested the latest version;
            feature not available
          required: true
  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description:
        Tell us about your feature request, more importantly, what is the
        end-user experience you are trying to build that led to the need for
        this feature?
      placeholder:
        'Describe you feature and tell why it will be beneficial adding to EDS'
    validations:
      required: true
  - type: textarea
    id: expected-solution
    attributes:
      label: Proposed Solution
      description:
        Describe your proposed solution, including how it should work and what
        you aim to accomplish. Providing context helps us develop a more
        practical solution.
      placeholder: |
        Explain how you propose to solve the problem, reference any relevant code from your project, and provide code samples demonstrating how the API would work once implemented.
    validations:
      required: true
  - type: textarea
    id: additional-reference
    attributes:
      label: Additional Information
      description:
        Provide a link to the Design specification, other libraries references
        as examples of the solution, or screenshots and videos of the expected
        behavior.
      placeholder: |
        You can drag your video or image files inside of this editor ↓
    validations:
      required: true
  - type: dropdown
    id: feature-priority
    attributes:
      label: Priority
      description:
        Please let us know how critical this feature is to you. Your feedback
        helps us prioritize effectively.
      options:
        - '🔴 Critical - Blocks key functionality or major feature releases'
        - '🟠 High - Affects features; temporary workaround is sufficient'
        - '🟡 Medium - Minor; inconvenience or cosmetic feature'
        - '🔵 Low - Non-essential, but would be nice to add'
    validations:
      required: true
  - type: checkboxes
    id: terms
    attributes:
      label: Terms
      description:
        By submitting this issue, you agree to verify that you have followed the
        requirements outlined above to the best of your ability.
      options:
        - label: I've made research efforts and searched the documentation
          required: true
